DROP DATABASE IF EXISTS DB_ORDER
GO

CREATE DATABASE DB_ORDER
GO

USE DB_ORDER
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Orders](
	[OrderId] INT IDENTITY(1,1) NOT NULL,
	[ProductName] VARCHAR(100) NOT NULL,
	[Quantity] INT NOT NULL,
	[Paid] BIT NOT NULL,
	[Shipped] BIT NOT NULL,
CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED([OrderId] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY])
ON [PRIMARY]
GO